### ISSUE TITLE
Secure storage: if an unsecured offline token already exists, the app falls back to basic auth

### ISSUE THREAD

**Issue by DonWillems** [openremote/console-android#14]
Reproduce:
1. install v1.0.3 of project K
2. Log in
3. Install v1.0.4 of project K
4. Open the app: it shows a white screen until the provider times out and then basic auth

It should be able to deal with the unsecure token, and overwrite it with a new one (after log in of the user)

**Comment by pierrekil** [comment]
@Miggets7 did find the issue? Is it resolved now?

**Comment by Miggets7** [comment]
Can't find the issue, because the fix @richturner made makes it work properly. It's not clear what exactly goed wrong.

I do see this message coming from the javascript code:
`Failed to retrieve data from storage provider`


But when looking at the typescript code, I can't find that print log statement

**Comment by richturner** [comment]
When it goes wrong the typescript code sends a provider message requesting the `offline token` during keycloak initialisation.

The native Android code fails to respond to the storage provider request which is why you see `Failed to retrieve data from storage provider` this message comes from `console.ts:377`.

The storage provider should never fail to respond, even if an exception occurs in the native code it should log and then return null
